In [1]:
import pandas as pd
from pyscenic.aucell import aucell
from pyscenic.utils import load_motifs
from pyscenic.utils import GeneSignature
import numpy as np
import os
import pickle
import scanpy as sc

/home/annikafomm/miniconda3/envs/aucell_env/lib/python3.10/site-packages/ctxcore/__init__.py:5: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution

In [2]:
os.getcwd()

'/home/annikafomm/University_Subject_Repos/mopitas-mapra/backend'

In [3]:
data_dir = "data"

In [4]:
# Read matrix from mtx file
matrix = sc.read_mtx("/home/annikafomm/University_Subject_Repos/mopitas-mapra/backend/data/CID3586/count_matrix_sparse.mtx").T
# Read genes and barcodes
genes = pd.read_csv("/home/annikafomm/University_Subject_Repos/mopitas-mapra/backend/data/CID3586/count_matrix_genes.tsv", sep="\t", header=None)
barcodes = pd.read_csv("/home/annikafomm/University_Subject_Repos/mopitas-mapra/backend/data/CID3586/count_matrix_barcodes.tsv", sep="\t", header=None)

               0
10        SAMD11
11         NOC2L
12        KLHL17
13       PLEKHN1
14         PERM1
15  RP11-54O7.17
16          HES4
17         ISG15
18          AGRN
19  RP11-54O7.18

In [5]:
anndata = sc.AnnData(X=matrix.X, obs=barcodes, var=genes)

/home/annikafomm/miniconda3/envs/aucell_env/lib/python3.10/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/home/annikafomm/miniconda3/envs/aucell_env/lib/python3.10/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [13]:
# Normalize the data
sc.pp.normalize_total(anndata, target_sum=1e6)
# Logarithmize the data
sc.pp.log1p(anndata)

In [14]:
# Filter
sc.pp.filter_cells(anndata, min_genes=200)
sc.pp.filter_genes(anndata, min_cells=3)

In [6]:
anndata.shape

(6178, 29733)

In [28]:
# convert to df
df = pd.DataFrame(anndata.X.toarray(), index=anndata.obs.index, columns=anndata.var[0])

In [16]:
# Read genie3 regulons
genie3 = pd.read_csv(
   f"{data_dir}/genie3_BRCA_mrn.top_100k.csv",
    index_col=0,
)

In [17]:
# Create GeneSets from genie3 regulons
genesets = []
for regulator, group in genie3.groupby("regulatoryGene"):
    gene2weight = dict(zip(group["targetGene"], group["weight"]))
    geneset = GeneSignature(name=regulator, gene2weight=gene2weight)
    genesets.append(geneset)

In [27]:
anndata.var

                   0  n_cells
2         FO538757.2      442
3         AP006222.2       46
5       RP5-857K21.4        3
6      RP11-206L10.9      104
7          LINC00115       61
...              ...      ...
21159     AL354822.1        9
21160     AC004556.1       55
21161     AC233755.2        6
21162     AC233755.1        6
21163     AC240274.1        5

[17944 rows x 2 columns]

In [29]:
# Overlap regulons with genes in the data
genie3_genes = set(genie3["targetGene"].unique())
genes_in_data = set(df.columns)
overlap_genes = genie3_genes.intersection(genes_in_data)
print(f"Number of genes in genie3 regulons: {len(genie3_genes)}")
print(f"Number of genes in data: {len(genes_in_data)}")
print(f"Number of overlapping genes: {len(overlap_genes)}")

Number of genes in genie3 regulons: 17339
Number of genes in data: 17944
Number of overlapping genes: 14159

In [18]:
genesets

[GeneSignature(name='ADNP', gene2weight=frozendict.frozendict({'TOP2B': 0.0279155260750008, 'EGFL7': 0.0237409127547856, 'RASIP1': 0.0206077146851765, 'ABCD4': 0.0198264699957939, 'CLDN5': 0.0196923416113006, 'DCLRE1A': 0.0196791886852008, 'UBXN2B': 0.0186096779888699, 'DHX40': 0.0175653551076977, 'FEM1B': 0.0169275218517057, 'UPP1': 0.0167412548801931, 'INHBC': 0.0164379980511868, 'ZNF146': 0.0162366041101673, 'CLDN15': 0.0162188588231912, 'SUV420H1': 0.0162154303199169, 'FBXO21': 0.0161746744825105, 'LYL1': 0.0161460409470039, 'GTF3C4': 0.0159948001546787, 'CHML': 0.0155638331522917, 'PPP2R5B': 0.0153062509862445, 'EXOC3L2': 0.015090823235948, 'FES': 0.0149996808025288, 'RBAK': 0.014902061047451, 'KAT7': 0.0148831899298347, 'RASSF1': 0.014873103380482, 'TADA1': 0.0147882868342616, 'RBBP4': 0.0146250663555892, 'PLD3': 0.0145239365173512, 'TMEM150A': 0.014377200370458, 'IKBKG': 0.0143513116808776, 'SIN3A': 0.013912341210591, 'TNFRSF1A': 0.0138251453401087, 'SLC27A3': 0.0137148123313428, 'PRIM1': 0.0136303055973491, 'SLC8B1': 0.0135991217291751, 'E2F4': 0.0135927701451826, 'TOMM20': 0.0135825300101987, 'PSTPIP1': 0.0135311640415899, 'TSPAN4': 0.0134718150523127, 'RP11-218L14.4': 0.0133484923982124, 'HPCAL1': 0.0131200666068322, 'TCIRG1': 0.0130639345487066, 'PLCB1': 0.0129997531678411, 'POLR1B': 0.0129948861956153, 'NOS3': 0.012923453481989})),
 GeneSignature(name='ADNP2', gene2weight=frozendict.frozendict({'USP6NL': 0.0210306335987131, 'SLC29A3': 0.0146738867233709, 'KIAA0930': 0.0144615967195303, 'TTC17': 0.0134403401996616, 'SLC16A12': 0.0132115391391301, 'CD52': 0.0130074891518003})),
 GeneSignature(name='AEBP1', gene2weight=frozendict.frozendict({'P4HA3': 0.0303534396465758, 'TMEM119': 0.0301438423944541, 'COL6A2': 0.0298833721893382, 'ADGRA2': 0.0297775867632795, 'GJC2': 0.0297374927922103, 'CPXM2': 0.0283400241139887, 'C3': 0.0281801456646983, 'MMP2': 0.0280242009873728, 'C1R': 0.0272121126216319, 'PCDHGC3': 0.0263930785417491, 'MMP23B': 0.0259450263438961, 'FBLN1': 0.0256423755335295, 'RCN3': 0.0253157693220079, 'CHRD': 0.0251320730863807, 'PCOLCE': 0.0248632608379291, 'OLFML3': 0.0239206690667375, 'CPZ': 0.0232194918594294, 'ADCY3': 0.0221089567391026, 'GRAP': 0.0220237736998542, 'FLNC': 0.0220165971229669, 'SFRP2': 0.021819447264294, 'MRC2': 0.0217720607884717, 'MRPS35': 0.0209075212264726, 'CALML4': 0.0208922290257975, 'C1QTNF5': 0.020890583681305, 'ISLR': 0.0206809129327951, 'OAF': 0.0206202260958954, 'EMILIN2': 0.0204356952592714, 'THBS3': 0.0203569800874864, 'RAB3IL1': 0.0199850254354609, 'GLIS2': 0.019859220307554, 'MMP23A': 0.0196955896449123, 'ADAM33': 0.0193466229783413, 'GLI1': 0.0193368099524808, 'FBLN7': 0.019301100131905, 'GRID1': 0.0192748281646639, 'ELN': 0.0191106399172507, 'LRRC4': 0.0187535853071005, 'ARHGAP23': 0.0187508111610248, 'APOL1': 0.0185616157684823, 'COL6A1': 0.0185196366004482, 'RAMP3': 0.018021275225632, 'AC144831.3': 0.0177661015448158, 'TNXB': 0.017697105625045, 'NOS3': 0.0176421757039892, 'KCTD17': 0.0176350887121933, 'RAB44': 0.0175844746302476, 'OLFML2B': 0.0174989375192238, 'PDGFRL': 0.0174938782435886, 'BGN': 0.0172233282890543, 'CTSG': 0.0172142417724398, 'CTSK': 0.0172000478399288, 'HIC1': 0.0170957721819221, 'COL1A2': 0.0170636392160796, 'ITGA5': 0.0170275785225054, 'MAN1C1': 0.0169671966490467, 'NBL1': 0.0169005554385958, 'VWCE': 0.0168838346757954, 'PODN': 0.0168389780136259, 'HSPA12B': 0.0168372387483757, 'LSP1': 0.0165062012999382, 'AHNAK2': 0.0163765611179195, 'PXN': 0.0162849342321921, 'C1QTNF9B': 0.0162360449504133, 'FCN1': 0.01621583708875, 'DUS4L': 0.0161886328015182, 'TBX5-AS1': 0.0159026027183335, 'SPON2': 0.0158840522254392, 'MEGF6': 0.0157906623811833, 'GALNT18': 0.0157597050856393, 'RP11-417E7.1': 0.0157133949015537, 'SRRM3': 0.0151989634266177, 'CNPY4': 0.0151593015259838, 'CALHM2': 0.0150512907446524, 'IGFBP4': 0.014875116879745, 'TSPAN11': 0.0148472477327363, 'HAND2': 0.0146077166057038, 'FLT4': 0.0141646578643967, 'SLIT3': 0.0141575444982196, 'F10': 0.0141099549757375, 'CFP': 0.0139154917427555, 'LCN6': 0.0138173160445783, 'TPSAB1': 0.013810099658865, 'DHH': 0.0137989371763907, 'ACP1': 0.0137942969854846, 'IGFBP6': 0.0137243004851828, 'NFATC4': 0.0136820209766204, 'SSC5D': 0.0135837332303326, 'SPNS2': 0.013456358757186, 'SCN1B': 0.0132802977284542, 'PPM1F': 0.0131964101757886, 'DACT3': 0.0131528340973537, 'IL2RA': 0.0131443450769401, 'COL6A3': 0.0131017506693322, 'THBS2': 0.0130471735338363, 'PLTP': 0.0130438319267414, 'PHYHIP': 0.0130331476492474, 'CRYBB1': 0.0129321911097306, 'OMA1': 0.0129310218548454, 'C1S': 0.0128803915534112, 'SHC1': 0.0128745921732776, 'RBM18': 0.0128410278753617, 'TMEM173': 0.0127536352471726, 'PAPLN': 0.0126716305794377})),
 GeneSignature(name='AEBP2', gene2weight=frozendict.frozendict({'RNF138': 0.0353718696152006, 'RYBP': 0.0250352252838552, 'STXBP3': 0.0249610878020946, 'CAAP1': 0.0243839807020694, 'CCDC126': 0.0237236691028655, 'PEX13': 0.0209348883852066, 'PELI1': 0.0198810366399489, 'B3GNT2': 0.0198733040306107, 'RNF2': 0.0198573983671225, 'SCAMP1': 0.019472079455962, 'MOSPD1': 0.01881351888144, 'ABHD13': 0.0185957444074801, 'TWISTNB': 0.0183705307810546, 'KLHL23': 0.0181514062694517, 'C5orf28': 0.0180500854577011, 'HNRNPLL': 0.0180263446765613, 'PTBP2': 0.017623089974975, 'WWTR1': 0.0173604299392998, 'TRA2A': 0.0172044141383045, 'FAM133B': 0.0170888790015515, 'FAS': 0.0170529321645648, 'ZNF487': 0.0170098148187497, 'NUS1': 0.0169193741421998, 'AC092171.4': 0.0168542027612291, 'C7orf60': 0.0167355753632688, 'IPMK': 0.0167326443726474, 'ZBTB21': 0.0167034600530466, 'RP11-1149O23.2': 0.0165667091798023, 'TMPO': 0.016455156480257, 'CTC-246B18.10': 0.0163565682145422, 'NUPL2': 0.0158662011165689, 'DENND6A': 0.0157978780155069, 'SMEK1': 0.015601580901532, 'DIMT1': 0.0154179112723416, 'INTS6': 0.0154084875212041, 'RP11-362K14.6': 0.0149923669028718, 'SRSF7': 0.0148587140158989, 'TMEM65': 0.0142603875861401, 'CBFB': 0.0140729215050268, 'BIRC2': 0.0139548080914022, 'CSNK1G3': 0.0138317200252186, 'TRA2B': 0.0138121742993658, 'TERF1': 0.0135920176765926, 'KPNA5': 0.0135512728326318, 'NUDCD1': 0.0130006096777342, 'TMEM263': 0.0128464714734211, 'PAPD5': 0.0126868544332567})),
 GeneSignature(name='AHCTF1', gene2weight=frozendict.frozendict({'PDPK1': 0.0251029089218213, 'SETD2': 0.0250665592782878, 'BSCL2': 0.023920444705261, 'UPF2': 0.023511405575954, 'CTD-2192J16.22': 0.0225006883765492, 'RP11-274B21.14': 0.0224978637488928, 'SPEN': 0.0212056962741379, 'MED1': 0.020945551921129, 'CAMSAP2': 0.019986083099992, 'BOD1L1': 0.0196197024309127, 'SLK': 0.0195706898007256, 'CNFN': 0.0195001301912809, 'TRAPPC10': 0.0194641144125852, 'USP8': 0.0190412852096567, 'NCOA1': 0.0190139042591845, 'NINJ1': 0.0190104941048782, 'INO80': 0.018811593082643, 'TPR': 0.0187757673675798, 'TXNDC17': 0.0185787887461066, 'ESF1': 0.0183922050416608, 'USP32': 0.0183352074438403, 'ZNF318': 0.0181648421097145, 'RP11-449H3.3': 0.0180708082308523, 'RABGAP1': 0.0180014816591539, 'RP1-198K11.5': 0.0179743417655811, 'APC': 0.0179202273222179, 'EP300': 0.0177134551839042, 'KDM3B': 0.0176140164841237, 'OVCA2': 0.0174688826400081, 'NCOA3': 0.0173568677918935, 'RP11-159G9.5': 0.0172052591016072, 'KIDINS220': 0.0170811568562565, 'NCOA6': 0.0170578387228358, 'RP11-298J20.4': 0.0170382506375967, 'TRAPPC11': 0.0170022645002014, 'RPS6KB1': 0.0169454401362353, 'RP11-274B21.1': 0.0169394678283128, 'MAD2L1BP': 0.0169058224273827, 'INAFM2': 0.0168747809444079, 'CEP170P1': 0.0168543833179937, 'PRAF2': 0.0166346966581824, 'AC011558.5': 0.0166179068624524, 'ICE1': 0.016604836286136, 'PSENEN': 0.0165324789610257, 'TMEM14A': 0.0162228220865592, 'NBEAL1': 0.0162011760131666, 'BAZ2A': 0.0160244054983765, 'CKAP5': 0.0159171570344857, 'TAF2': 0.0157900932678455, 'KDM5A': 0.0157871659378661, 'CTD-2231E14.8': 0.0157602979628379, 'C9orf16': 0.015737683145922, 'FAM168A': 0.0156534666855871, 'SHPRH': 0.0155714150267402, 'SF3B4': 0.015479829582487, 'RP11-529E10.6': 0.0154384777108946, 'MBTPS2': 0.0154075643316436, 'KIAA1109': 0.0153925937515055, 'C17orf49': 0.0153835380201909, 'DIS3': 0.0153336471489476, 'GOLGA8R': 0.0152965507110373, 'SNX13': 0.0151953241566025, 'ZNRD1': 0.0151831662494173, 'NIPBL': 0.015162798007848, 'PLEKHM3': 0.0151557826699095, 'MAX': 0.0151158168920664, 'NUP160': 0.0150618576252142, 'PHF3': 0.0150521532138812, 'GOLGA4': 0.0150248082177444, 'TAF1': 0.0150189378234633, 'CCDC144B': 0.0150064888206031, 'PHF20L1': 0.0149887386077444, 'TMEM219': 0.0149071339290959, 'LY6G5C': 0.0147334323895691, 'SBNO1': 0.0146799337770526, 'SAYSD1': 0.0146779135679623, 'TTC3P1': 0.0146522017828532, 'TAF10': 0.0146441859810363, 'FXYD5': 0.0146248228810703, 'TOPBP1': 0.0146243594705486, 'FOXJ3': 0.0146194857131357, 'DMXL1': 0.0145978131517188, 'CASP8AP2': 0.0145805703178175, 'ZC3H13': 0.0145769888498363, 'MFAP3': 0.0145525250425546, 'ASXL2': 0.0145221912703047, 'RP11-20I23.8': 0.0145068902731751, 'ARFGEF2': 0.0144451398491591, 'STRN': 0.0144126592147081, 'S100A16': 0.01440245949894, 'NFX1': 0.0143918607161184, 'GCOM1': 0.0143166368014152, 'HMG20A': 0.0142519914612635, 'WDR26': 0.0142510667058438, 'PPIG': 0.0142252253159326, 'KIF2A': 0.0141392051649934, 'RBM33': 0.0141119423363188, 'ZFR': 0.014072867280428, 'NEK1': 0.0140568302329639, 'UTP14C': 0.0140554405980106, 'DHX29': 0.0140533259828204, 'ZNF384': 0.014010302125819, 'SSR4': 0.0139421452615971, 'RALGAPA1': 0.0139398036484621, 'HECTD1': 0.0139240320495841, 'AP4E1': 0.0138613395563334, 'RANBP2': 0.0138103782197813, 'ZNF407': 0.013782249815939, 'DZIP3': 0.0137816309573901, 'STX17': 0.013740468726963, 'CDK12': 0.0136245980303462, 'RP11-746M1.1': 0.0136236429628808, 'ZZEF1': 0.0135952830375435, 'KAT6A': 0.013566247457124, 'AC009487.6': 0.0135394538386378, 'CEP192': 0.0135314002948187, 'GPATCH8': 0.0135301062952925, 'DPM2': 0.0135280163763404, 'DENND4A': 0.0135103669255547, 'MKLN1': 0.0134973722261432, 'CLP1': 0.0134871867999134, 'ALG11': 0.0134749223422108, 'ATF7': 0.0134675973995267, 'MED13L': 0.0134508160230726, 'TTC21B': 0.0134287462727049, 'KIF21A': 0.0133870289766518, 'ERH': 0.0133852473733855, 'SON': 0.0132412985167085, 'RP1-34H18.1': 0.0131689350980248, 'LIN54': 0.0131479055233032, 'TCAF1P1': 0.0131395646826839, 'C6orf1': 0.0130833600953697, 'CNOT1': 0.0130605682860991, 'ZNF770': 0.0130523945177753, 'VPS13C': 0.0130460843930415, 'RP11-498C9.15': 0.0130437886247939, 'ZBED6': 0.0130369587461686, 'PIK3R4': 0.0129974468929834, 'CPEB4': 0.0129882270765115, 'HP1BP3': 0.012962350899607, 'CLASP1': 0.0129578980925139, 'FKBP1B': 0.0129343159923512, 'CTC-444N24.8': 0.0129143375031938, 'SKIV2L2': 0.0129040681815918, 'RCOR1': 0.0128798964148508, 'DYNLT1': 0.0128582807195432, 'PATL1': 0.0128284477557606, 'PUM1': 0.0128216727117234, 'ALS2': 0.0128163830498236, 'CEP350': 0.0128025500159948, 'RB1CC1': 0.0127851391792003, 'MED19': 0.0127724176039564, 'ITCH': 0.0127440829652485, 'RALGAPA1P': 0.0127400950631578, 'STAG2': 0.0127003781921011})),
 GeneSignature(name='AHDC1', gene2weight=frozendict.frozendict({'ZNF710': 0.0290948244005952, 'MAPKBP1': 0.0236996926712021, 'DNAJC25': 0.0224732847959791, 'UNC50': 0.0224532658792959, 'DAGLA': 0.0210344365820124, 'MKL1': 0.0208463224988644, 'NCK2': 0.0202933821557618, 'RP11-363E7.4': 0.0196823020681146, 'ZNF74': 0.019216477322795, 'RASA4CP': 0.0188658023661548, 'LLGL1': 0.0188164627239626, 'CREBL2': 0.0187934937426329, 'RAI1': 0.0187631467155573, 'DBH-AS1': 0.0185196769371621, 'DAG1': 0.0184655611472529, 'HS6ST1P1': 0.0182563723184242, 'TMEM50B': 0.0175336789850946, 'SMARCA4': 0.0172903574987417, 'KRBA1': 0.0172212004485313, 'LZTS3': 0.0169362234052747, 'RP11-123K3.4': 0.0169264073909344, 'DOK7': 0.0169162726309545, 'NDFIP1': 0.0167729227026757, 'PDCD11': 0.0166118096130675, 'FBN3': 0.0161649661074547, 'MCM2': 0.0161306593907736, 'PGRMC2': 0.0161191551808419, 'MYBBP1A': 0.0160625752872422, 'GOLGA2P7': 0.015958495421015, 'RP11-378J18.8': 0.0158621739128233, 'DPH1': 0.0157832711869307, 'VPS26A': 0.0157134319205617, 'USP11': 0.0157085120800788, 'CHERP': 0.0155608497293506, 'ZNF853': 0.0153364855526451, 'SEPT5': 0.0152988955149019, 'C4orf32': 0.0152715133170468, 'RP11-449P15.1': 0.0152682928184559, 'CTD-2132N18.2': 0.0150822443254201, 'CCNH': 0.0150623853471839, 'FOXK2': 0.0150042077881475, 'CHMP5': 0.0150018488450293, 'RNASE4': 0.014850014314937, 'MICALL1': 0.0147123275214531, 'DNMT1': 0.0146714087589465, 'SMO': 0.0146707381340427, 'SREBF2': 0.0143376984476209, 'DLGAP1-AS1': 0.0142671967728638, 'LRCH4': 0.0142569434015701, 'CAMK2B': 0.0142511952475729, 'LYPLAL1': 0.0142242307194992, 'FAM107B': 0.01422170668391, 'FAM184B': 0.0141937152324182, 'CCDC152': 0.0141931002165515, 'DHX34': 0.0141138713657698, 'CCDC134': 0.0141097641158314, 'RAP1B': 0.0140824800021385, 'DOT1L': 0.0140668619429763, 'SEC62': 0.0140432003796351, 'TEAD3': 0.013885267688246, 'ACOT11': 0.0138484950242177, 'GRIK5': 0.0137172839965897, 'DNAJC25-GNG10': 0.0136661292760733, 'RIN1': 0.0136123200394461, 'MADD': 0.013461513937625, 'ARL6IP1': 0.0134485563378926, 'TNNT2': 0.0133358164803567, 'YPEL5': 0.0133215830545185, 'NOL6': 0.0132570984330753, 'ZCCHC9': 0.0131980256555383, 'DAB2IP': 0.0131717372389974, 'DCTN6': 0.0131609166341205, 'CLEC16A': 0.013091435758953, 'ROGDI': 0.0130600585744274, 'RP11-482H16.1': 0.0129470486682597, 'NIPSNAP3A': 0.0129306155567067, 'ZMIZ2': 0.012906450813435, 'WRNIP1': 0.0129026178871498, 'HPDL': 0.0128120168979121, 'RP11-182J1.3': 0.0127214806391679, 'HS6ST1': 0.0126863579398924, 'CIC': 0.0126753206576816})),
 GeneSignature(name='AHR', gene2weight=frozendict.frozendict({'DCXR': 0.0223165581027064, 'RNF167': 0.0207325430306168, 'P2RX7': 0.0197415384132734, 'FAM134C': 0.0195458051276566, 'SLC39A10': 0.019111597267742, 'UGCG': 0.0189697132586108, 'ZDHHC20': 0.0181534734663057, 'GBP1': 0.0171950056441475, 'FAM122B': 0.0168123897818373, 'NCOA7': 0.0166749917859164, 'SPRED1': 0.0166617004322363, 'GEM': 0.0164906629203454, 'STX18': 0.0163545993178457, 'RP1-68D18.4': 0.0156250195775635, 'VPS72': 0.0155771564675351, 'TECR': 0.0152603352550268, 'SMUG1': 0.0151899944825025, 'FAS': 0.0151734441212563, 'RABGAP1L': 0.0150478897713556, 'WDR25': 0.0150393179885718, 'CTB-113I20.2': 0.0149230873327374, 'MYEOV2': 0.0144768354683285, 'VPS52': 0.0144305667243682, 'YTHDF3-AS1': 0.0144077954089783, 'ZNHIT3': 0.0142326134092917, 'SNRNP25': 0.0140363808626037, 'SPR': 0.0139418059562335, 'MIR155HG': 0.0139246633914698, 'NPRL3': 0.0137358198243387, 'RP11-1149O23.2': 0.0135170510922371, 'POLR2I': 0.013317356410383, 'PMF1-BGLAP': 0.0133099723653055, 'ZBTB21': 0.0132926450048595, 'SLC30A7': 0.0132814821882679, 'CTD-2256P15.2': 0.0132702017605274, 'ATP10D': 0.0131349649303003, 'PNPLA4': 0.0129247375224361, 'HIF1A': 0.0128873560792757, 'TOLLIP-AS1': 0.0128282132660968, 'DYRK3': 0.012738749537672})),
 GeneSignature(name='AKAP8', gene2weight=frozendict.frozendict({'FIP1L1': 0.0185154290989325, 'ZXDC': 0.016240384495349, 'TM7SF3': 0.0149211073634624, 'RP11-15A1.7': 0.0144462371928511, 'CYB561D1': 0.0141900911684355, 'RP4-781K5.2': 0.013938136962142, 'SDHAP1': 0.013190127429307})),
 GeneSignature(name='AKAP8L', gene2weight=frozendict.frozendict({'SAFB2': 0.023935601109086, 'SH2B1': 0.0235932805388713, 'FKBP7': 0.0223346663167791, 'DHX16': 0.0216110739976465, 'KRI1': 0.0211758758669273, 'CLASRP': 0.0206088857836637, 'RGS12': 0.0205127318754686, 'SAFB': 0.0203797535896252, 'CLK3': 0.0199692379953928, 'PRKRIP1': 0.0195645731930716, 'SUPT5H': 0.0195507728709411, 'PHRF1': 0.0187030028940771, 'CDK11A': 0.018216373383829, 'CCER2': 0.0180113674493312, 'CCDC130': 0.0178948861881087, 'SNRNP70': 0.0170309983655058, 'IGHMBP2': 0.0168920064199601, 'CCDC9': 0.0167104752376759, 'CCHCR1': 0.0166471252483805, 'RBM19': 0.0166458952189721, 'POLR3E': 0.0161574293263605, 'MAP2K7': 0.016088099498896, 'CHTOP': 0.016077905690211, 'OBSL1': 0.0159889565747992, 'MTHFSD': 0.0158936699726561, 'ZNF646': 0.0158307580980123, 'ZNF839': 0.0156655766960852, 'MBD1': 0.0154449678562456, 'WASH3P': 0.0153911212692158, 'RP11-661A12.8': 0.0153394966283845, 'ZBTB22': 0.0152968186121734, 'E4F1': 0.0150526008637644, 'MARK4': 0.0150343688922629, 'SRRT': 0.0149991026204853, 'SMG7-AS1': 0.0149794642594933, 'SSR1': 0.0148591482003093, 'HACD4': 0.0148082019304682, 'ZC3H18': 0.0146734846722224, 'NEURL4': 0.0146697019808108, 'RP4-583P15.15': 0.0146340024309986, 'RRNAD1': 0.0145957663858185, 'TUT1': 0.0145464926269922, 'ACIN1': 0.0145222180327052, 'RSAD1': 0.014494780957322, 'PLA2G4B': 0.0144722670725976, 'FBRS': 0.0144564015388771, 'BBC3': 0.0144356524098571, 'ZNF316': 0.0143620969527947, 'D2HGDH': 0.0143435326132652, 'TAF15': 0.0143288213523537, 'RP11-61J19.5': 0.0142264477133531, 'RP4-614O4.13': 0.0140488539357575, 'ANAPC2': 0.0140460946993562, 'CHAF1A': 0.0140346645799265, 'ZBTB48': 0.0140001446847979, 'RHOT2': 0.0139245231781646, 'UBTF': 0.0139133609553308, 'CTA-29F11.1': 0.0138887881184381, 'AF127936.5': 0.0137380814122324, 'KLHDC4': 0.0137340730364966, 'RP11-649E7.5': 0.0133470273577131, 'CYTH2': 0.0132601130778, 'EWSR1': 0.0132533727304083, 'PPAN': 0.0132360337547665, 'UBLCP1': 0.01322842919625, 'HDAC11': 0.0131652371773763, 'TNK2': 0.0129110742391679, 'TCOF1': 0.0128832733352215, 'REXO1': 0.0128486567777631, 'CTD-2639E6.9': 0.0126739403002486})),
 GeneSignature(name='AKNA', gene2weight=frozendict.frozendict({'SPOCK2': 0.0264566157956253, 'RASGRP2': 0.0210252641412625, 'PSTPIP1': 0.0208011859224536, 'UBA7': 0.0205962052013095, 'NLRC5': 0.020273200174841, 'TNFRSF25': 0.0190854998597522, 'CIITA': 0.0184331410668426, 'C11orf21': 0.0173107353029052, 'FGD2': 0.0161689401364792, 'LCAT': 0.0160447584510094, 'FUT7': 0.0154264101604266, 'OLA1': 0.0151098156495882, 'TNRC6C-AS1': 0.0151036545778408, 'RP11-876N24.3': 0.0148370607347949, 'RP11-1391J7.1': 0.0146701530370565, 'VASH1': 0.0143308652389902, 'CCDC17': 0.0141360996016547, 'DENND4B': 0.0139988581046272, 'USP30-AS1': 0.0139406156091278, 'CACTIN-AS1': 0.0138772120658111, 'FAM78A': 0.0135749548723495, 'TRPC2': 0.0134964880469178, 'KLHL6': 0.0133540361999018, 'ITGB7': 0.0133118876011211, 'MYO1F': 0.0132734192547546, 'RP11-876N24.4': 0.0132721664950837, 'RP5-1171I10.5': 0.0132405276328493, 'INPP5E': 0.0126861890150373})),
 GeneSignature(name='ALX4', gene2weight=frozendict.frozendict({'HPSE2': 0.0287076550009738, 'RP11-255H23.4': 0.0238557779113656, 'CAPN6': 0.0191344048898209, 'NTRK1': 0.0181163717151926, 'TMEM213': 0.0176075790359138, 'CACNA1G': 0.0169623103187647, 'TMC3-AS1': 0.0167221831465611, 'GPRC5D': 0.0166874635770694, 'NOV': 0.016464812272371, 'CRACR2A': 0.0159414387835477, 'LAMC3': 0.0156896261108345, 'FRRS1L': 0.0154550364509495, 'ZNF488': 0.0153720836553826, 'DCX': 0.0152173360099508, 'SUFU': 0.0148455275295437, 'KCNMB2': 0.0147899405521223, 'ASTN1': 0.0144234132729317, 'FZD10': 0.0143546062778868, 'WARS': 0.0143308407009749, 'CYP19A1': 0.0142897123257664, 'TMEM130': 0.0140134204339773, 'LAMA1': 0.0136300159067175, 'PCP4L1': 0.0135688325875754, 'BHLHA15': 0.0133752763779365, 'TM6SF1': 0.0132488413449063, 'FMN2': 0.0130704749490936, 'ENPP6': 0.0130310830400207, 'SEMA4G': 0.012746852139895, 'RP11-768F21.1': 0.0127106180915708, 'RP4-794I6.4': 0.0126479456884855})),

In [30]:
aucell_results = aucell(
    df,
    genesets,
    num_workers=8
)

Less than 80% of the genes in ZNF366 are present in the expression matrix.
Less than 80% of the genes in ETV5 are present in the expression matrix.
Less than 80% of the genes in ONECUT2 are present in the expression matrix.
Less than 80% of the genes in FAM200B are present in the expression matrix.
Less than 80% of the genes in AKAP8 are present in the expression matrix.
Less than 80% of the genes in OTX1 are present in the expression matrix.
Less than 80% of the genes in ALX4 are present in the expression matrix.
Less than 80% of the genes in ANKZF1 are present in the expression matrix.
Less than 80% of the genes in ARHGAP35 are present in the expression matrix.
Less than 80% of the genes in JRK are present in the expression matrix.
Less than 80% of the genes in ARID3A are present in the expression matrix.
Less than 80% of the genes in TBPL1 are present in the expression matrix.
Less than 80% of the genes in TBX1 are present in the expression matrix.
Less than 80% of the genes in PAX2 are present in the expression matrix.
Less than 80% of the genes in PAX8 are present in the expression matrix.
Less than 80% of the genes in ZFP92 are present in the expression matrix.
Less than 80% of the genes in PAX9 are present in the expression matrix.
Less than 80% of the genes in ARX are present in the expression matrix.
Less than 80% of the genes in FOXA3 are present in the expression matrix.
Less than 80% of the genes in TBX19 are present in the expression matrix.
Less than 80% of the genes in FOXC1 are present in the expression matrix.
Less than 80% of the genes in TBX2 are present in the expression matrix.
Less than 80% of the genes in FOXC2 are present in the expression matrix.
Less than 80% of the genes in FOXD1 are present in the expression matrix.
Less than 80% of the genes in PBX3 are present in the expression matrix.
Less than 80% of the genes in FOXD2 are present in the expression matrix.
Less than 80% of the genes in ASH1L are present in the expression matrix.
Less than 80% of the genes in TBX3 are present in the expression matrix.
Less than 80% of the genes in TBX4 are present in the expression matrix.
Less than 80% of the genes in ZNF630 are present in the expression matrix.
Less than 80% of the genes in FOXD4L1 are present in the expression matrix.
Less than 80% of the genes in FOXD4L5 are present in the expression matrix.
Less than 80% of the genes in FOXF2 are present in the expression matrix.
Less than 80% of the genes in KIN are present in the expression matrix.
Less than 80% of the genes in FOXH1 are present in the expression matrix.
Less than 80% of the genes in ZNF641 are present in the expression matrix.
Less than 80% of the genes in ZNF37A are present in the expression matrix.
Less than 80% of the genes in ZGLP1 are present in the expression matrix.
Less than 80% of the genes in ZNF382 are present in the expression matrix.
Less than 80% of the genes in PEG3 are present in the expression matrix.
Less than 80% of the genes in PGR are present in the expression matrix.
Less than 80% of the genes in ATF4 are present in the expression matrix.
Less than 80% of the genes in ATF5 are present in the expression matrix.
Less than 80% of the genes in ZNF648 are present in the expression matrix.
Less than 80% of the genes in PHF21A are present in the expression matrix.
Less than 80% of the genes in TCF23 are present in the expression matrix.
Less than 80% of the genes in ZNF385B are present in the expression matrix.
Less than 80% of the genes in ZNF652 are present in the expression matrix.
Less than 80% of the genes in FOXK1 are present in the expression matrix.
Less than 80% of the genes in FOXL1 are present in the expression matrix.
Less than 80% of the genes in PITX1 are present in the expression matrix.
Less than 80% of the genes in ZIC1 are present in the expression matrix.
Less than 80% of the genes in PKNOX2 are present in the expression matrix.
Less than 80% of the genes in ZIC2 are present in the expression matrix.
Less than 80% of the genes in TCF7L1 are present in the expression matrix.
Less than 80% of the genes in ZIM2 are present in the expression matrix.
Less than 80% of the genes in ZKSCAN1 are present in the expression matrix.
Less than 80% of the genes in TCFL5 are present in the expression matrix.
Less than 80% of the genes in ZKSCAN2 are present in the expression matrix.
Less than 80% of the genes in ZNF397 are present in the expression matrix.
Less than 80% of the genes in ZNF66 are present in the expression matrix.
Less than 80% of the genes in POU2AF1 are present in the expression matrix.
Less than 80% of the genes in ZNF662 are present in the expression matrix.
Less than 80% of the genes in ZNF407 are present in the expression matrix.
Less than 80% of the genes in POU2F1 are present in the expression matrix.
Less than 80% of the genes in ZNF665 are present in the expression matrix.
Less than 80% of the genes in ZMAT1 are present in the expression matrix.
Less than 80% of the genes in ZMAT4 are present in the expression matrix.
Less than 80% of the genes in POU2F3 are present in the expression matrix.
Less than 80% of the genes in POU5F1B are present in the expression matrix.
Less than 80% of the genes in ZNF671 are present in the expression matrix.
Less than 80% of the genes in POU5F2 are present in the expression matrix.
Less than 80% of the genes in ZNF101 are present in the expression matrix.
Less than 80% of the genes in ZNF672 are present in the expression matrix.
Less than 80% of the genes in ZNF674 are present in the expression matrix.
Less than 80% of the genes in ZNF415 are present in the expression matrix.
Less than 80% of the genes in BAZ2A are present in the expression matrix.
Less than 80% of the genes in ZNF676 are present in the expression matrix.
Less than 80% of the genes in ZNF417 are present in the expression matrix.
Less than 80% of the genes in ZNF418 are present in the expression matrix.
Less than 80% of the genes in ZNF117 are present in the expression matrix.
Less than 80% of the genes in FOXP3 are present in the expression matrix.
Less than 80% of the genes in L3MBTL1 are present in the expression matrix.
Less than 80% of the genes in ZNF121 are present in the expression matrix.
Less than 80% of the genes in ZNF124 are present in the expression matrix.
Less than 80% of the genes in FOXS1 are present in the expression matrix.
Less than 80% of the genes in ZNF682 are present in the expression matrix.
Less than 80% of the genes in ZNF132 are present in the expression matrix.
Less than 80% of the genes in ZNF425 are present in the expression matrix.
Less than 80% of the genes in ZNF684 are present in the expression matrix.
Less than 80% of the genes in ZNF135 are present in the expression matrix.
Less than 80% of the genes in LEF1 are present in the expression matrix.
Less than 80% of the genes in PRDM16 are present in the expression matrix.
Less than 80% of the genes in LHX2 are present in the expression matrix.
Less than 80% of the genes in BHLHA15 are present in the expression matrix.
Less than 80% of the genes in LHX4 are present in the expression matrix.
Less than 80% of the genes in BHLHE22 are present in the expression matrix.
Less than 80% of the genes in PRDM5 are present in the expression matrix.
Less than 80% of the genes in ZNF689 are present in the expression matrix.
Less than 80% of the genes in BNC1 are present in the expression matrix.
Less than 80% of the genes in ZNF69 are present in the expression matrix.
Less than 80% of the genes in PRDM8 are present in the expression matrix.
Less than 80% of the genes in TFAP2E are present in the expression matrix.
Less than 80% of the genes in GBX2 are present in the expression matrix.
Less than 80% of the genes in GCM1 are present in the expression matrix.
Less than 80% of the genes in PROX1 are present in the expression matrix.
Less than 80% of the genes in PROX2 are present in the expression matrix.
Less than 80% of the genes in ZNF696 are present in the expression matrix.
Less than 80% of the genes in TFDP1 are present in the expression matrix.
Less than 80% of the genes in ZNF44 are present in the expression matrix.
Less than 80% of the genes in GLIS1 are present in the expression matrix.
Less than 80% of the genes in ZNF70 are present in the expression matrix.
Less than 80% of the genes in ZNF700 are present in the expression matrix.
Less than 80% of the genes in ZNF155 are present in the expression matrix.
Less than 80% of the genes in ZNF443 are present in the expression matrix.
Less than 80% of the genes in ZNF701 are present in the expression matrix.
Less than 80% of the genes in ZNF157 are present in the expression matrix.
Less than 80% of the genes in ZNF445 are present in the expression matrix.
Less than 80% of the genes in PURG are present in the expression matrix.
Less than 80% of the genes in ZNF160 are present in the expression matrix.
Less than 80% of the genes in ZNF705E are present in the expression matrix.
Less than 80% of the genes in GLYR1 are present in the expression matrix.
Less than 80% of the genes in CCDC17 are present in the expression matrix.
Less than 80% of the genes in GMEB1 are present in the expression matrix.
Less than 80% of the genes in ZNF449 are present in the expression matrix.
Less than 80% of the genes in RARB are present in the expression matrix.
Less than 80% of the genes in ZNF169 are present in the expression matrix.
Less than 80% of the genes in CDX1 are present in the expression matrix.
Less than 80% of the genes in ZNF17 are present in the expression matrix.
Less than 80% of the genes in MAX are present in the expression matrix.
Less than 80% of the genes in TGIF1 are present in the expression matrix.
Less than 80% of the genes in ZNF460 are present in the expression matrix.
Less than 80% of the genes in TGIF2 are present in the expression matrix.
Less than 80% of the genes in ZNF177 are present in the expression matrix.
Less than 80% of the genes in ZNF18 are present in the expression matrix.
Less than 80% of the genes in CEBPB are present in the expression matrix.
Less than 80% of the genes in THAP10 are present in the expression matrix.
Less than 80% of the genes in ZNF467 are present in the expression matrix.
Less than 80% of the genes in THAP11 are present in the expression matrix.
Less than 80% of the genes in ZNF182 are present in the expression matrix.
Less than 80% of the genes in CEBPG are present in the expression matrix.
Less than 80% of the genes in ZNF714 are present in the expression matrix.
Less than 80% of the genes in ZNF19 are present in the expression matrix.
Less than 80% of the genes in ZNF474 are present in the expression matrix.
Less than 80% of the genes in ZNF726 are present in the expression matrix.
Less than 80% of the genes in ZNF727 are present in the expression matrix.
Less than 80% of the genes in GRHL3 are present in the expression matrix.
Less than 80% of the genes in ZNF728 are present in the expression matrix.
Less than 80% of the genes in GSC are present in the expression matrix.
Less than 80% of the genes in ZNF732 are present in the expression matrix.
Less than 80% of the genes in ZNF483 are present in the expression matrix.
Less than 80% of the genes in ZNF736 are present in the expression matrix.
Less than 80% of the genes in ZNF484 are present in the expression matrix.
Less than 80% of the genes in CENPT are present in the expression matrix.
Less than 80% of the genes in ZNF202 are present in the expression matrix.
Less than 80% of the genes in GTF2I are present in the expression matrix.
Less than 80% of the genes in MECP2 are present in the expression matrix.
Less than 80% of the genes in GTF2IRD2 are present in the expression matrix.
Less than 80% of the genes in GTF2IRD2B are present in the expression matrix.
Less than 80% of the genes in ZNF208 are present in the expression matrix.
Less than 80% of the genes in RFX2 are present in the expression matrix.
Less than 80% of the genes in ZNF490 are present in the expression matrix.
Less than 80% of the genes in ZNF211 are present in the expression matrix.
Less than 80% of the genes in RFX3 are present in the expression matrix.
Less than 80% of the genes in ZNF491 are present in the expression matrix.
Less than 80% of the genes in ZNF749 are present in the expression matrix.
Less than 80% of the genes in HAND2 are present in the expression matrix.
Less than 80% of the genes in RHOXF1 are present in the expression matrix.
Less than 80% of the genes in ZNF75A are present in the expression matrix.
Less than 80% of the genes in HES1 are present in the expression matrix.
Less than 80% of the genes in HES2 are present in the expression matrix.
Less than 80% of the genes in TIGD2 are present in the expression matrix.
Less than 80% of the genes in ZNF221 are present in the expression matrix.
Less than 80% of the genes in RORB are present in the expression matrix.
Less than 80% of the genes in TIGD4 are present in the expression matrix.
Less than 80% of the genes in ZNF224 are present in the expression matrix.
Less than 80% of the genes in ZNF763 are present in the expression matrix.
Less than 80% of the genes in HESX1 are present in the expression matrix.
Less than 80% of the genes in MESP2 are present in the expression matrix.
Less than 80% of the genes in HEYL are present in the expression matrix.
Less than 80% of the genes in ZNF229 are present in the expression matrix.
Less than 80% of the genes in ZNF232 are present in the expression matrix.
Less than 80% of the genes in HIC2 are present in the expression matrix.
Less than 80% of the genes in ZNF233 are present in the expression matrix.
Less than 80% of the genes in MIXL1 are present in the expression matrix.
Less than 80% of the genes in ZNF234 are present in the expression matrix.
Less than 80% of the genes in MKX are present in the expression matrix.
Less than 80% of the genes in CREBZF are present in the expression matrix.
Less than 80% of the genes in ZNF236 are present in the expression matrix.
Less than 80% of the genes in ZNF773 are present in the expression matrix.
Less than 80% of the genes in ZNF239 are present in the expression matrix.
Less than 80% of the genes in MLXIP are present in the expression matrix.
Less than 80% of the genes in ZNF248 are present in the expression matrix.
Less than 80% of the genes in ZNF516 are present in the expression matrix.
Less than 80% of the genes in HIVEP3 are present in the expression matrix.
Less than 80% of the genes in RXRG are present in the expression matrix.
Less than 80% of the genes in TRERF1 are present in the expression matrix.
Less than 80% of the genes in CTCF are present in the expression matrix.
Less than 80% of the genes in MNX1 are present in the expression matrix.
Less than 80% of the genes in MSANTD1 are present in the expression matrix.
Less than 80% of the genes in ZNF518B are present in the expression matrix.
Less than 80% of the genes in ZNF251 are present in the expression matrix.
Less than 80% of the genes in CUX2 are present in the expression matrix.
Less than 80% of the genes in HMBOX1 are present in the expression matrix.
Less than 80% of the genes in ZNF256 are present in the expression matrix.
Less than 80% of the genes in TSHZ2 are present in the expression matrix.
Less than 80% of the genes in CXXC5 are present in the expression matrix.
Less than 80% of the genes in ZNF782 are present in the expression matrix.
Less than 80% of the genes in TTF1 are present in the expression matrix.
Less than 80% of the genes in TWIST1 are present in the expression matrix.
Less than 80% of the genes in DBP are present in the expression matrix.
Less than 80% of the genes in DBX2 are present in the expression matrix.
Less than 80% of the genes in MSX2 are present in the expression matrix.
Less than 80% of the genes in ZNF785 are present in the expression matrix.
Less than 80% of the genes in MTERF2 are present in the expression matrix.
Less than 80% of the genes in ZNF264 are present in the expression matrix.
Less than 80% of the genes in ZNF266 are present in the expression matrix.
Less than 80% of the genes in MTERF3 are present in the expression matrix.
Less than 80% of the genes in DLX1 are present in the expression matrix.
Less than 80% of the genes in ZNF528 are present in the expression matrix.
Less than 80% of the genes in DLX2 are present in the expression matrix.
Less than 80% of the genes in ZNF529 are present in the expression matrix.
Less than 80% of the genes in HOXA1 are present in the expression matrix.
Less than 80% of the genes in DLX5 are present in the expression matrix.
Less than 80% of the genes in SETDB1 are present in the expression matrix.
Less than 80% of the genes in DLX6 are present in the expression matrix.
Less than 80% of the genes in ZNF788 are present in the expression matrix.
Less than 80% of the genes in ZNF540 are present in the expression matrix.
Less than 80% of the genes in ZNF789 are present in the expression matrix.
Less than 80% of the genes in DMRT2 are present in the expression matrix.
Less than 80% of the genes in ZNF541 are present in the expression matrix.
Less than 80% of the genes in ZNF275 are present in the expression matrix.
Less than 80% of the genes in HOXA11 are present in the expression matrix.
Less than 80% of the genes in ZNF544 are present in the expression matrix.
Less than 80% of the genes in DMTF1 are present in the expression matrix.
Less than 80% of the genes in HOXA3 are present in the expression matrix.
Less than 80% of the genes in SHOX2 are present in the expression matrix.
Less than 80% of the genes in HOXA4 are present in the expression matrix.
Less than 80% of the genes in ZNF547 are present in the expression matrix.
Less than 80% of the genes in WT1 are present in the expression matrix.
Less than 80% of the genes in MYB are present in the expression matrix.
Less than 80% of the genes in SIX1 are present in the expression matrix.
Less than 80% of the genes in ZNF549 are present in the expression matrix.
Less than 80% of the genes in SIX2 are present in the expression matrix.
Less than 80% of the genes in ZNF550 are present in the expression matrix.
Less than 80% of the genes in SIX3 are present in the expression matrix.
Less than 80% of the genes in HOXA9 are present in the expression matrix.
Less than 80% of the genes in HOXB2 are present in the expression matrix.
Less than 80% of the genes in MYC are present in the expression matrix.
Less than 80% of the genes in HOXB3 are present in the expression matrix.
Less than 80% of the genes in HOXB4 are present in the expression matrix.
Less than 80% of the genes in HOXB6 are present in the expression matrix.
Less than 80% of the genes in ZNF554 are present in the expression matrix.
Less than 80% of the genes in YBX3 are present in the expression matrix.
Less than 80% of the genes in ZNF284 are present in the expression matrix.
Less than 80% of the genes in ZNF81 are present in the expression matrix.
Less than 80% of the genes in YY2 are present in the expression matrix.
Less than 80% of the genes in ZNF286B are present in the expression matrix.
Less than 80% of the genes in SMAD1 are present in the expression matrix.
Less than 80% of the genes in HOXB8 are present in the expression matrix.
Less than 80% of the genes in MYRF are present in the expression matrix.
Less than 80% of the genes in ZNF814 are present in the expression matrix.
Less than 80% of the genes in HOXB9 are present in the expression matrix.
Less than 80% of the genes in HOXC10 are present in the expression matrix.
Less than 80% of the genes in HOXC11 are present in the expression matrix.
Less than 80% of the genes in MYSM1 are present in the expression matrix.
Less than 80% of the genes in HOXC12 are present in the expression matrix.
Less than 80% of the genes in MYT1 are present in the expression matrix.
Less than 80% of the genes in HOXC13 are present in the expression matrix.

In [35]:
# How many zero
zero_aucell = np.sum(aucell_results > 0.4)
print(f"Number of zero AUC values: {zero_aucell}")

Number of zero AUC values: Regulon
ADNP      0
ADNP2     2
AEBP1     0
AEBP2     0
AHCTF1    0
         ..
ZUFSP     1
ZXDA      0
ZXDB      0
ZXDC      0
ZZZ3      0
Length: 1317, dtype: int64

/home/annikafomm/.local/lib/python3.10/site-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

In [32]:
aucell_results

Regulon,ADNP,ADNP2,AEBP1,AEBP2,AHCTF1,AHDC1,AHR,AKAP8,AKAP8L,AKNA,...,ZSCAN30,ZSCAN31,ZSCAN32,ZSCAN5A,ZSCAN9,ZUFSP,ZXDA,ZXDB,ZXDC,ZZZ3
Cell,,,,,,,,,,,,,,,,,,,,,
0,0.073757,0.000000,0.026134,0.012075,0.037737,0.021775,0.025082,0.0,0.024222,0.000000,...,0.0,0.093116,0.0,0.137058,0.0,0.000000,0.070847,0.0,0.063067,0.015920
1,0.061586,0.104632,0.014302,0.043846,0.044343,0.007694,0.043143,0.0,0.000456,0.017544,...,0.0,0.000000,0.0,0.076432,0.0,0.102862,0.059253,0.0,0.037151,0.036915
2,0.106515,0.000000,0.042316,0.021742,0.021213,0.019465,0.013981,0.0,0.012200,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.272715,0.087389,0.0,0.053213,0.020991
3,0.074674,0.000000,0.027540,0.022461,0.040027,0.011126,0.049362,0.0,0.022232,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.070933,0.0,0.074991,0.036627
4,0.093071,0.000000,0.039556,0.023466,0.021460,0.008754,0.024180,0.0,0.036773,0.054009,...,0.0,0.000000,0.0,0.071885,0.0,0.000000,0.000000,0.0,0.035081,0.050394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6173,0.016139,0.006649,0.004530,0.020003,0.041510,0.028890,0.014931,0.0,0.019643,0.025924,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.033083,0.0,0.057058,0.019234
6174,0.002398,0.000000,0.000000,0.013655,0.036230,0.003913,0.007890,0.0,0.000000,0.027476,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.073057,0.0,0.077264,0.018470
6175,0.005618,0.000000,0.003601,0.055859,0.018742,0.013662,0.040363,0.0,0.028865,0.008627,...,0.0,0.111649,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.071542,0.018189
6176,0.023997,0.010789,0.002763,0.018676,0.018669,0.033116,0.014664,0.0,0.019504,0.020532,...,0.0,0.000000,0.0,0.115189,0.0,0.000000,0.000000,0.0,0.072823,0.015660
6177,0.004602,0.000000,0.004134,0.026503,0.034606,0.009714,0.042536,0.0,0.046301,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.009061