In [1]:
import pandas as pd
import requests
from io import StringIO

In [2]:

go0030199_genes = [
    "CRTAP","P3H4","EMILIN1","ADAMTS7","ANTXR2","COL1A1","COL1A2","COL2A1",
    "COL3A1","COL4A1","COL4A2","COL4A3","COL4A4","COL4A5","COL4A6","COL5A1",
    "COL5A2","COL6A1","COL7A1","COL11A1","COL11A2","COL12A1","COMP","ADAMTS14",
    "CHADL","CYP1B1","AEBP1","ADAMTS19","DPT","EXT1","FOXC1","FOXC2","COLGALT2",
    "FMOD","OPTC","VPS33B","GREM1","P4HA3","ERO1A","EFEMP2","ANXA2","COL28A1",
    "LOX","LOXL1","LOXL2","LUM","MIR29B1","MMP11","NF1","DDR2","P4HA1","COL5A3",
    "SERPINF2","PLOD1","PLOD2","ATP7A","SELENON","RB1","FKBP10","VIPAS39","P3H1",
    "SFRP2","SCX","BMP1","TGFB2","TGFBR1","TLL1","TLL2","TNXB","COL14A1","PXDN",
    "COLGALT1","ADAMTS12","LOXL4","LOXL3","SERPINH1","PLOD3","ADAMTS3","ADAMTS2"
]

url = "https://omnipathdb.org/interactions/"
params = {
    "genesymbols": 1,
    "datasets": "collectri",
    "organisms": 9606,
    "targets": ",".join(go0030199_genes),
    "fields": "sources,references"
}

r = requests.get(url, params=params, timeout=60)
r.raise_for_status()

raw = pd.read_csv(StringIO(r.text), sep="\t")

gene_tf_df = (
    raw[["target_genesymbol", "source_genesymbol"]]
    .rename(columns={"target_genesymbol": "gene", "source_genesymbol": "TF"})
    .dropna()
    .drop_duplicates()
    .sort_values(["gene", "TF"])
    .reset_index(drop=True)
)

gene_tf_df

        gene       TF
0    ADAMTS7       HR
1    ADAMTS7  HTATIP2
2    ADAMTS7    SSRP1
3    ADAMTS7   TFAP2A
4    ADAMTS7   ZBTB16
..       ...      ...
623   TGFBR1      SP1
624   TGFBR1   TFAP2A
625     TLL1   NKX2-5
626     TNXB      SP1
627   VPS33B    STAT1

[628 rows x 2 columns]

In [9]:
gene_tf_df.to_csv("objects_AVN_fibroblast/gene_tf_relations_AVN_fibroblasts.csv", index=False)

In [2]:
gene_tf_df = pd.read_csv("objects_AVN_fibroblast/gene_tf_relations_AVN_fibroblasts.csv")

In [4]:
gene_tf_df[gene_tf_df["gene"] == "COL1A1"]

      gene       TF
39  COL1A1    CEBPB
40  COL1A1    CEBPD
41  COL1A1    CIITA
42  COL1A1  CREB3L1
43  COL1A1     DLX5
44  COL1A1     EGR1
45  COL1A1     ETS1
46  COL1A1     HES1
47  COL1A1     LEF1
48  COL1A1    MEF2A
49  COL1A1    MRTFA
50  COL1A1     MSX2
51  COL1A1      MYB
52  COL1A1    MYBL2
53  COL1A1   NFATC1
54  COL1A1   NFATC4
55  COL1A1     NFIC
56  COL1A1    NFKB1
57  COL1A1   NOTCH1
58  COL1A1    NR1H4
59  COL1A1    NR4A2
60  COL1A1     RELA
61  COL1A1    RUNX2
62  COL1A1      SCX
63  COL1A1    SMAD3
64  COL1A1    SMAD4
65  COL1A1    SMAD7
66  COL1A1      SP1
67  COL1A1      SP3
68  COL1A1      SP7
69  COL1A1    SRSF2
70  COL1A1    STAT6
71  COL1A1   TFAP2A
72  COL1A1      VDR
73  COL1A1     YBX1
74  COL1A1      YY1
75  COL1A1   ZBTB16
76  COL1A1   ZBTB7B
77  COL1A1     ZEB1
78  COL1A1   ZNF384

In [8]:
len(gene_tf_df["gene"].unique())

52

In [14]:

gene_tf_df[(gene_tf_df["gene"] == "COL1A2") & (gene_tf_df["TF"] == "RUNX2")]

       gene     TF
138  COL1A2  RUNX2